select
    Id as patient_id,
    BIRTHDATE,
    DEATHDATE,
    SSN,
    DRIVERS,
    PASSPORT,
    PREFIX,
    "FIRST" as first_name,
    "LAST" as last_name,
    SUFFIX,
    MAIDEN,
    MARITAL,
    RACE,
    ETHNICITY,
    GENDER,
    BIRTHPLACE,
    ADDRESS,
    CITY,
    STATE,
    COUNTY,
    ZIP,
    LAT,
    LON,
    HEALTHCARE_EXPENSES,
    HEALTHCARE_COVERAGE
from {{ source('synthea','patients') }}